# Generated by Django 2.1.7 on 2019-03-30 11:33

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import movies_api.models.movie


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('edited', models.DateField(auto_now=True)),
                ('text', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(max_length=32)),
                ('title', models.CharField(db_index=True, max_length=128)),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1895), movies_api.models.movie.max_value_current_year])),
                ('rated', models.CharField(max_length=16, null=True)),
                ('released', models.DateField(null=True)),
                ('runtime', models.DurationField(null=True)),
                ('genres', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), null=True, size=None)),
                ('director', models.CharField(max_length=128, null=True)),
                ('writer', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), null=True, size=None)),
                ('actors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), null=True, size=None)),
                ('plot', models.TextField(null=True)),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), null=True, size=None)),
                ('country', models.CharField(max_length=128, null=True)),
                ('awards', models.TextField(null=True)),
                ('poster', models.URLField(null=True)),
                ('ratings', django.contrib.postgres.fields.jsonb.JSONField()),
                ('metascore', models.PositiveSmallIntegerField(null=True)),
                ('imdb_rating', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('imdb_votes', models.IntegerField(null=True)),
                ('type', models.CharField(max_length=64)),
                ('dvd', models.DateField(null=True)),
                ('box_office', models.IntegerField(null=True)),
                ('production', models.CharField(max_length=128, null=True)),
                ('website', models.URLField(null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='movie',
            unique_together={('imdb_id', 'title')},
        ),
        migrations.AddField(
            model_name='comment',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='movies_api.Movie'),
        ),
    ]
