# Generated by Django 2.1.7 on 2019-03-27 19:08

import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import movies_api.models.movie


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(max_length=32)),
                ('title', models.CharField(db_index=True, max_length=128)),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1895), movies_api.models.movie.max_value_current_year])),
                ('rated', models.CharField(choices=[('General Audiences', 'G'), ('Parental Guidance Suggested', 'PG'), ('Parents Strongly Cautioned', 'PG-13'), ('Restricted', 'R'), ('Adults Only', 'NC-17')], default='G', max_length=8)),
                ('released', models.DateField()),
                ('runtime', models.DurationField(validators=[django.core.validators.MaxValueValidator(999)])),
                ('genre', models.CharField(max_length=128, null=True)),
                ('director', models.CharField(max_length=128, null=True)),
                ('writer', models.CharField(max_length=128, null=True)),
                ('actors', models.CharField(max_length=512, null=True)),
                ('plot', models.TextField(null=True)),
                ('language', models.CharField(max_length=64, null=True)),
                ('country', models.CharField(max_length=128, null=True)),
                ('awards', models.TextField(null=True)),
                ('poster', models.URLField(null=True)),
                ('ratings', django.contrib.postgres.fields.jsonb.JSONField()),
                ('metascore', models.PositiveSmallIntegerField(null=True)),
                ('imdb_rating', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('imdb_votes', models.IntegerField(null=True)),
                ('type', models.CharField(max_length=64)),
                ('dvd', models.DateField(null=True)),
                ('box_office', models.IntegerField(null=True)),
                ('production', models.CharField(max_length=128, null=True)),
                ('website', models.URLField(null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='movie',
            unique_together={('imdb_id', 'title')},
        ),
    ]
