# Generated by Django 2.1.7 on 2019-03-27 20:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_api', '0003_auto_20190327_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='runtime',
            field=models.DurationField(null=True, validators=[django.core.validators.MaxValueValidator(999)]),
        ),
    ]
