# Generated by Django 2.1.7 on 2019-03-27 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_api', '0006_auto_20190327_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rated',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
