# Generated by Django 2.1.7 on 2019-03-27 22:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_api', '0007_auto_20190327_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='writer',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), null=True, size=None),
        ),
    ]
